#!/bin/bash
#
# adds charm's yum repo as a source to any rpm-based linux distro

if [[ -e '/etc/yum.repos.d/' ]]; then
	printf "[charm]\nname=Charm\nbaseurl=https://repo.charm.sh/yum/\nenabled=1\ngpgcheck=1\ngpgkey=https://repo.charm.sh/yum/gpg.key" | tee /etc/yum.repos.d/charm.repo
fi