#!/bin/bash
#
# installs neofetch on an rpm-based image. defaults to version 8 if /etc/os-release isn't found

if command -v neofetch &> /dev/null; then
  echo "neofetch installed."
  if command -v starship &> /dev/null; then
    echo "starship also installed. nothing to do."
    exit
  fi
fi

if [[ -e /etc/os-release ]] && grep -q 'VERSION_ID=\S' /etc/os-release ; then
  # shellcheck source=/dev/null
  source /etc/os-release
else
  VERSION_ID="8"
fi

dnf install "https://dl.fedoraproject.org/pub/epel/epel-release-latest-${VERSION_ID:0:1}.noarch.rpm" -y
dnf install neofetch -y


dnf copr enable atim/starship -y

yum install starship -y

#TODO install ascii/terminal.ans to ~/ascii/ directory
cp ../ascii/ ~/Documents/

if ! grep -q neofetch "$HOME/.bashrc"; then
  echo 'neofetch --source ~/Documents/ascii/terminal.ans --gap -15' >> ~/.bashrc
  # SC2016 checks for proper variable expansion
  # shellcheck disable=SC2016
  echo 'eval "$(starship init bash)"' >> ~/.bashrc
else
  echo "neofetch is already included in $HOME/.bashrc. No action taken"
fi
