#!/bin/bash
#
# installs gum from charm's yum repo. 
# adds charm's yum repo if charm is not installed.

if command -v gum &> /dev/null; then
	gum style "gum is already installed. nothing to do." --foreground=3
	exit
fi

if [[ ! -e '/etc/yum.repos.d/' ]]; then
	echo -e "\e[31m the /etc/yum.repos.d directory doesn't exist. is this an rpm-based image?\e[0m\nexiting"
	exit
fi
if [[ ! -e '/etc/yum.repos.d/charm.repo'  ]]; then
	echo -e "\e[90mAdding the charm yum repo in /etc/yum.repos.d/charm.repo...\e[0m"
	echo -e "[charm]\nname=Charm\nbaseurl=https://repo.charm.sh/yum/\nenabled=1\ngpgcheck=1\ngpgkey=https://repo.charm.sh/yum/gpg.key" > /etc/yum.repos.d/charm.repo
fi

yum install gum -y

if command -v gum &> /dev/null; then
	gum style 'gum is installed!' --foreground=10 --border-foreground=13 --border="rounded" --padding="0 1" --italic --background=8 --border-background=8
else
	echo "gum failed to install. that's all I know"
fi

# if [[ -e ~/.bashrc ]]; then
# 	sed -i '/# User specific aliases and functions/a'
# fi