#!/bin/bash
#
# installs the specified charm package from charm's yum repo

function install-charm() {
  # ----- validate install is actually needed ----
  # querying yum to validate an install is much slower than testing if a package can be used.
  packages=("$@")
  for package in "$@"; do
    if command -v "$package" &>/dev/null; then
      echo -e "\t\e[33$package is already installed. nothing to do.\e[0m"
      packages=( "${packages[@]/$package/}" ) # remove from list of packages to install
    fi
  done
  if [ "${#packages[@]}" == 0 ]; then
    echo -e "the requested charm package(s) $* are already installed. nothing to do.\e[0m"
    exit
  fi

  # ----- add charm's yum repo ------
  if [[ ! -e '/etc/yum.repos.d/' ]]; then
    echo -e "\t\e[32m the /etc/yum.repos.d directory doesn't exist. is this an rpm-based image?\e[0m\n\texiting"
    exit
  fi
  if [[ ! -e '/etc/yum.repos.d/charm.repo' ]]; then
    echo -e "\t\e[90mAdding the charm yum repo in /etc/yum.repos.d/charm.repo\e[0m"
    echo -e "[charm]\nname=Charm\nbaseurl=https://repo.charm.sh/yum/\nenabled=1\ngpgcheck=1\ngpgkey=https://repo.charm.sh/yum/gpg.key" >/etc/yum.repos.d/charm.repo
  fi

  yum install "${packages[@]}" -y

  # ---- validate installs ----
  for package in "${packages[@]}"; do
    if command -v "$package" &>/dev/null; then
      echo -e "\t\e[34m$package was successfully installe!\e[0m"
    else
      echo -e "\t\e[31m$package failed to install. that's all I know\e[0m"
    fi
  done
}
